### ISSUE TITLE
Enhancements and feature updates

### ISSUE THREAD

**Issue by hasan-haider** [hasan-haider/flask_url_shortener#1]
Creating contribution.md
and new ideas on how to enhance this project will be helpful

**Comment by alxtrnr** [comment]
May I help with creating the contribution.md?

**Comment by hasan-haider** [comment]
> May I help with creating the contribution.md?

Sure. Also some feature recommendations will be helpful.

**Comment by alxtrnr** [comment]
Thanks. My first pull request on github and for hacktoberfest. Hope it fits the remit.

**Comment by hasan-haider** [comment]
> Thanks. My first pull request on github and for hacktoberfest. Hope it fits the remit.

Thank you for your contribution. Hope this contribution helps you too.
